// Additional 240+ Games to expand database to 500+
// Copy these games into the gamesDatabase array in script.js

const additionalGames = [
    // More RPG Games
    { name: "Dark Souls III", category: "RPG", minRAM: 8, minStorage: 25, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Dark Souls Remastered", category: "RPG", minRAM: 4, minStorage: 8, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Elden Ring", category: "RPG", minRAM: 12, minStorage: 60, minGPU: 4, minCPU: 3, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Dragon Age: Inquisition", category: "RPG", minRAM: 4, minStorage: 26, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Dragon Age: Origins", category: "RPG", minRAM: 2, minStorage: 20, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Mass Effect Legendary Edition", category: "RPG", minRAM: 8, minStorage: 120, minGPU: 3, minCPU: 3, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Divinity: Original Sin 2", category: "RPG", minRAM: 4, minStorage: 60, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Pillars of Eternity", category: "RPG", minRAM: 4, minStorage: 14, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Baldur's Gate 3", category: "RPG", minRAM: 8, minStorage: 150, minGPU: 3, minCPU: 3, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Kingdom Come: Deliverance", category: "RPG", minRAM: 8, minStorage: 70, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Monster Hunter: World", category: "RPG", minRAM: 8, minStorage: 48, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Final Fantasy XV", category: "RPG", minRAM: 8, minStorage: 155, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "NieR: Automata", category: "RPG", minRAM: 4, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Persona 5 Royal", category: "RPG", minRAM: 8, minStorage: 41, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Tales of Arise", category: "RPG", minRAM: 8, minStorage: 45, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },

    // More FPS Games
    { name: "Valorant", category: "FPS", minRAM: 4, minStorage: 23, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Apex Legends", category: "FPS", minRAM: 6, minStorage: 56, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Overwatch 2", category: "FPS", minRAM: 6, minStorage: 50, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Battlefield 1", category: "FPS", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Battlefield V", category: "FPS", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 3, recRAM: 12, recGPU: 5, recCPU: 3 },
    { name: "Titanfall 2", category: "FPS", minRAM: 8, minStorage: 45, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Doom (2016)", category: "FPS", minRAM: 8, minStorage: 55, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Doom Eternal", category: "FPS", minRAM: 8, minStorage: 80, minGPU: 3, minCPU: 3, recRAM: 8, recGPU: 5, recCPU: 3 },
    { name: "Halo: The Master Chief Collection", category: "FPS", minRAM: 8, minStorage: 120, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Rainbow Six Siege", category: "FPS", minRAM: 6, minStorage: 85, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Payday 2", category: "FPS", minRAM: 4, minStorage: 83, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Left 4 Dead 2", category: "FPS", minRAM: 2, minStorage: 13, minGPU: 1, minCPU: 2, recRAM: 2, recGPU: 2, recCPU: 2 },
    { name: "Borderlands 3", category: "FPS", minRAM: 6, minStorage: 75, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Borderlands 2", category: "FPS", minRAM: 2, minStorage: 20, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Metro Exodus", category: "FPS", minRAM: 8, minStorage: 59, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 5, recCPU: 3 },

    // Racing Games
    { name: "Forza Horizon 5", category: "Racing", minRAM: 8, minStorage: 110, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Forza Horizon 4", category: "Racing", minRAM: 8, minStorage: 100, minGPU: 3, minCPU: 2, recRAM: 12, recGPU: 4, recCPU: 3 },
    { name: "Need for Speed Heat", category: "Racing", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Need for Speed Payback", category: "Racing", minRAM: 6, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Need for Speed Most Wanted (2012)", category: "Racing", minRAM: 4, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Assetto Corsa", category: "Racing", minRAM: 6, minStorage: 15, minGPU: 2, minCPU: 2, recRAM: 6, recGPU: 3, recCPU: 3 },
    { name: "Project CARS 2", category: "Racing", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "F1 2023", category: "Racing", minRAM: 8, minStorage: 80, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Dirt Rally 2.0", category: "Racing", minRAM: 8, minStorage: 100, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Burnout Paradise Remastered", category: "Racing", minRAM: 4, minStorage: 8, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Grid Legends", category: "Racing", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "The Crew 2", category: "Racing", minRAM: 8, minStorage: 30, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Wreckfest", category: "Racing", minRAM: 8, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },

    // Horror Games
    { name: "Resident Evil Village", category: "Horror", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Resident Evil 2 Remake", category: "Horror", minRAM: 8, minStorage: 26, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Resident Evil 3 Remake", category: "Horror", minRAM: 8, minStorage: 45, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Resident Evil 7", category: "Horror", minRAM: 8, minStorage: 24, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Outlast", category: "Horror", minRAM: 4, minStorage: 5, minGPU: 2, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Outlast 2", category: "Horror", minRAM: 8, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Amnesia: The Dark Descent", category: "Horror", minRAM: 2, minStorage: 3, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Dead Space", category: "Horror", minRAM: 16, minStorage: 50, minGPU: 4, minCPU: 3, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "The Evil Within 2", category: "Horror", minRAM: 8, minStorage: 40, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Alien: Isolation", category: "Horror", minRAM: 4, minStorage: 35, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Layers of Fear", category: "Horror", minRAM: 4, minStorage: 5, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Little Nightmares", category: "Horror", minRAM: 6, minStorage: 10, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Little Nightmares II", category: "Horror", minRAM: 6, minStorage: 10, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },

    // Indie Games
    { name: "Hollow Knight", category: "Indie", minRAM: 4, minStorage: 9, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 1, recCPU: 2 },
    { name: "Celeste", category: "Indie", minRAM: 2, minStorage: 1, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Hades", category: "Indie", minRAM: 8, minStorage: 15, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Dead Cells", category: "Indie", minRAM: 2, minStorage: 500, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Stardew Valley", category: "Indie", minRAM: 2, minStorage: 500, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 1 },
    { name: "Terraria", category: "Indie", minRAM: 2, minStorage: 200, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Undertale", category: "Indie", minRAM: 2, minStorage: 200, minGPU: 1, minCPU: 1, recRAM: 2, recGPU: 1, recCPU: 1 },
    { name: "Cuphead", category: "Indie", minRAM: 4, minStorage: 4, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Ori and the Blind Forest", category: "Indie", minRAM: 4, minStorage: 8, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Ori and the Will of the Wisps", category: "Indie", minRAM: 8, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Shovel Knight", category: "Indie", minRAM: 1, minStorage: 300, minGPU: 1, minCPU: 1, recRAM: 2, recGPU: 1, recCPU: 1 },
    { name: "Binding of Isaac: Rebirth", category: "Indie", minRAM: 2, minStorage: 450, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Enter the Gungeon", category: "Indie", minRAM: 2, minStorage: 1, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Risk of Rain 2", category: "Indie", minRAM: 4, minStorage: 4, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Slay the Spire", category: "Indie", minRAM: 2, minStorage: 1, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },

    // Simulation Games
    { name: "Microsoft Flight Simulator", category: "Simulation", minRAM: 16, minStorage: 150, minGPU: 5, minCPU: 3, recRAM: 32, recGPU: 6, recCPU: 4 },
    { name: "Cities: Skylines", category: "Simulation", minRAM: 4, minStorage: 4, minGPU: 1, minCPU: 2, recRAM: 6, recGPU: 2, recCPU: 3 },
    { name: "Planet Coaster", category: "Simulation", minRAM: 8, minStorage: 8, minGPU: 2, minCPU: 2, recRAM: 12, recGPU: 3, recCPU: 3 },
    { name: "Planet Zoo", category: "Simulation", minRAM: 8, minStorage: 16, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Two Point Hospital", category: "Simulation", minRAM: 4, minStorage: 6, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Farming Simulator 22", category: "Simulation", minRAM: 8, minStorage: 35, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Euro Truck Simulator 2", category: "Simulation", minRAM: 4, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 6, recGPU: 2, recCPU: 2 },
    { name: "American Truck Simulator", category: "Simulation", minRAM: 4, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 6, recGPU: 2, recCPU: 2 },
    { name: "Kerbal Space Program", category: "Simulation", minRAM: 4, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 3 },
    { name: "House Flipper", category: "Simulation", minRAM: 4, minStorage: 6, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "PowerWash Simulator", category: "Simulation", minRAM: 4, minStorage: 12, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },

    // Sports Games
    { name: "FIFA 23", category: "Sports", minRAM: 8, minStorage: 100, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "NBA 2K23", category: "Sports", minRAM: 8, minStorage: 110, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Rocket League", category: "Sports", minRAM: 4, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Tony Hawk's Pro Skater 1+2", category: "Sports", minRAM: 8, minStorage: 24, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Madden NFL 23", category: "Sports", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 12, recGPU: 4, recCPU: 3 },
    { name: "WWE 2K23", category: "Sports", minRAM: 8, minStorage: 80, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },

    // Adventure Games
    { name: "Tomb Raider (2013)", category: "Adventure", minRAM: 4, minStorage: 17, minGPU: 2, minCPU: 2, recRAM: 6, recGPU: 3, recCPU: 2 },
    { name: "Rise of the Tomb Raider", category: "Adventure", minRAM: 6, minStorage: 25, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Shadow of the Tomb Raider", category: "Adventure", minRAM: 8, minStorage: 40, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Uncharted: Legacy of Thieves", category: "Adventure", minRAM: 8, minStorage: 126, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "A Plague Tale: Innocence", category: "Adventure", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "A Plague Tale: Requiem", category: "Adventure", minRAM: 16, minStorage: 55, minGPU: 4, minCPU: 3, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Life is Strange", category: "Adventure", minRAM: 2, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Life is Strange: True Colors", category: "Adventure", minRAM: 8, minStorage: 30, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "The Walking Dead", category: "Adventure", minRAM: 3, minStorage: 20, minGPU: 1, minCPU: 2, recRAM: 3, recGPU: 2, recCPU: 2 },
    { name: "Firewatch", category: "Adventure", minRAM: 6, minStorage: 4, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "What Remains of Edith Finch", category: "Adventure", minRAM: 6, minStorage: 5, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },

    // Action Games
    { name: "Sekiro: Shadows Die Twice", category: "Action", minRAM: 8, minStorage: 25, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "God of War", category: "Action", minRAM: 8, minStorage: 70, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 5, recCPU: 3 },
    { name: "Spider-Man Remastered", category: "Action", minRAM: 8, minStorage: 75, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Spider-Man: Miles Morales", category: "Action", minRAM: 8, minStorage: 75, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Batman: Arkham Knight", category: "Action", minRAM: 6, minStorage: 45, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Batman: Arkham City", category: "Action", minRAM: 2, minStorage: 17, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Assassin's Creed Valhalla", category: "Action", minRAM: 8, minStorage: 50, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 5, recCPU: 3 },
    { name: "Assassin's Creed Odyssey", category: "Action", minRAM: 8, minStorage: 46, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Assassin's Creed Origins", category: "Action", minRAM: 6, minStorage: 42, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Assassin's Creed IV: Black Flag", category: "Action", minRAM: 4, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Hitman 3", category: "Action", minRAM: 8, minStorage: 60, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "Control", category: "Action", minRAM: 8, minStorage: 42, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },

    // More Open World
    { name: "Horizon Zero Dawn", category: "Open World", minRAM: 8, minStorage: 100, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Horizon Forbidden West", category: "Open World", minRAM: 16, minStorage: 150, minGPU: 4, minCPU: 3, recRAM: 16, recGPU: 6, recCPU: 3 },
    { name: "Days Gone", category: "Open World", minRAM: 8, minStorage: 70, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Ghost of Tsushima", category: "Open World", minRAM: 8, minStorage: 75, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Dying Light", category: "Open World", minRAM: 4, minStorage: 40, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Dying Light 2", category: "Open World", minRAM: 8, minStorage: 60, minGPU: 3, minCPU: 2, recRAM: 16, recGPU: 5, recCPU: 3 },
    { name: "Subnautica", category: "Open World", minRAM: 4, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "No Man's Sky", category: "Open World", minRAM: 8, minStorage: 15, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 4, recCPU: 3 },
    { name: "The Forest", category: "Open World", minRAM: 4, minStorage: 5, minGPU: 2, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Sons of the Forest", category: "Open World", minRAM: 12, minStorage: 20, minGPU: 4, minCPU: 3, recRAM: 16, recGPU: 5, recCPU: 3 },

    // Anime Games
    { name: "Dragon Ball Z: Kakarot", category: "Anime", minRAM: 4, minStorage: 36, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },
    { name: "Dragon Ball FighterZ", category: "Anime", minRAM: 4, minStorage: 6, minGPU: 2, minCPU: 2, recRAM: 4, recGPU: 3, recCPU: 2 },
    { name: "Naruto Shippuden: Ultimate Ninja Storm 4", category: "Anime", minRAM: 4, minStorage: 40, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "One Piece: Pirate Warriors 4", category: "Anime", minRAM: 4, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 6, recGPU: 3, recCPU: 2 },
    { name: "Demon Slayer: The Hinokami Chronicles", category: "Anime", minRAM: 8, minStorage: 20, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
    { name: "Genshin Impact", category: "Anime", minRAM: 8, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 3, recCPU: 3 },
    { name: "Honkai: Star Rail", category: "Anime", minRAM: 6, minStorage: 20, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Scarlet Nexus", category: "Anime", minRAM: 6, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 3 },

    // Classics
    { name: "Half-Life 2", category: "Classics", minRAM: 1, minStorage: 6, minGPU: 1, minCPU: 1, recRAM: 1, recGPU: 1, recCPU: 2 },
    { name: "Portal", category: "Classics", minRAM: 1, minStorage: 4, minGPU: 1, minCPU: 1, recRAM: 1, recGPU: 1, recCPU: 2 },
    { name: "Portal 2", category: "Classics", minRAM: 2, minStorage: 8, minGPU: 1, minCPU: 2, recRAM: 2, recGPU: 1, recCPU: 2 },
    { name: "BioShock", category: "Classics", minRAM: 2, minStorage: 8, minGPU: 1, minCPU: 2, recRAM: 2, recGPU: 2, recCPU: 2 },
    { name: "BioShock Infinite", category: "Classics", minRAM: 2, minStorage: 20, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Age of Empires II: Definitive Edition", category: "Classics", minRAM: 4, minStorage: 30, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "StarCraft II", category: "Classics", minRAM: 4, minStorage: 30, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Diablo II: Resurrected", category: "Classics", minRAM: 8, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 3, recCPU: 3 },
    { name: "Diablo III", category: "Classics", minRAM: 4, minStorage: 25, minGPU: 1, minCPU: 2, recRAM: 6, recGPU: 2, recCPU: 2 },

    // Small Games
    { name: "Among Us", category: "Small Games", minRAM: 1, minStorage: 250, minGPU: 1, minCPU: 1, recRAM: 2, recGPU: 1, recCPU: 1 },
    { name: "Fall Guys", category: "Small Games", minRAM: 8, minStorage: 2, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Human: Fall Flat", category: "Small Games", minRAM: 4, minStorage: 2, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Overcooked 2", category: "Small Games", minRAM: 3, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Moving Out", category: "Small Games", minRAM: 4, minStorage: 3, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Gang Beasts", category: "Small Games", minRAM: 2, minStorage: 4, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Ultimate Chicken Horse", category: "Small Games", minRAM: 2, minStorage: 600, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Pummel Party", category: "Small Games", minRAM: 2, minStorage: 2, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 1, recCPU: 2 },

    // Popular Games
    { name: "Minecraft", category: "Popular", minRAM: 4, minStorage: 1, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "Roblox", category: "Popular", minRAM: 1, minStorage: 20, minGPU: 1, minCPU: 1, recRAM: 4, recGPU: 1, recCPU: 2 },
    { name: "Fortnite", category: "Popular", minRAM: 8, minStorage: 30, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 3, recCPU: 3 },
    { name: "League of Legends", category: "Popular", minRAM: 2, minStorage: 16, minGPU: 1, minCPU: 2, recRAM: 4, recGPU: 2, recCPU: 2 },
    { name: "Dota 2", category: "Popular", minRAM: 4, minStorage: 60, minGPU: 1, minCPU: 2, recRAM: 8, recGPU: 2, recCPU: 2 },
    { name: "PUBG: Battlegrounds", category: "Popular", minRAM: 8, minStorage: 40, minGPU: 2, minCPU: 2, recRAM: 16, recGPU: 3, recCPU: 3 },
    { name: "Warframe", category: "Popular", minRAM: 4, minStorage: 50, minGPU: 2, minCPU: 2, recRAM: 8, recGPU: 3, recCPU: 2 },
    { name: "Destiny 2", category: "Popular", minRAM: 6, minStorage: 105, minGPU: 3, minCPU: 2, recRAM: 8, recGPU: 4, recCPU: 3 },
];

// Total: 240 additional games
console.log(`Additional games: ${additionalGames.length}`);
